<?php

declare(strict_types=1);

// osfsl-C:/laragon/www/usk_no_ai/vendor/composer/../sentry/sentry-laravel/src/Sentry/Laravel/Console/TestCommand.php-PHPStan\BetterReflection\Reflection\ReflectionClass-Sentry\Laravel\Console\TestCommand
return \PHPStan\Cache\CacheItem::__set_state([
    'variableKey' => 'v2-6066375d0e86841018c9d2f1da436c36185f4112981e8d8f7997955f71189fa9-8.3.26-6.65.0.9',
    'data' => [
        'locatedSource' => [
            'class' => 'PHPStan\\BetterReflection\\SourceLocator\\Located\\LocatedSource',
            'data' => [
                'name' => 'Sentry\\Laravel\\Console\\TestCommand',
                'filename' => 'C:/laragon/www/usk_no_ai/vendor/composer/../sentry/sentry-laravel/src/Sentry/Laravel/Console/TestCommand.php',
            ],
        ],
        'namespace' => 'Sentry\\Laravel\\Console',
        'name' => 'Sentry\\Laravel\\Console\\TestCommand',
        'shortName' => 'TestCommand',
        'isInterface' => false,
        'isTrait' => false,
        'isEnum' => false,
        'isBackedEnum' => false,
        'modifiers' => 0,
        'docComment' => null,
        'attributes' => [
        ],
        'startLine' => 20,
        'endLine' => 256,
        'startColumn' => 1,
        'endColumn' => 1,
        'parentClassName' => 'Illuminate\\Console\\Command',
        'implementsClassNames' => [
        ],
        'traitClassNames' => [
        ],
        'immediateConstants' => [
        ],
        'immediateProperties' => [
            'signature' => [
                'declaringClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
                'implementingClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
                'name' => 'signature',
                'modifiers' => 2,
                'type' => null,
                'default' => [
                    'code' => '\'sentry:test {--transaction} {--dsn=}\'',
                    'attributes' => [
                        'startLine' => 22,
                        'endLine' => 22,
                        'startTokenPos' => 93,
                        'startFilePos' => 512,
                        'endTokenPos' => 93,
                        'endFilePos' => 549,
                    ],
                ],
                'docComment' => null,
                'attributes' => [
                ],
                'startLine' => 22,
                'endLine' => 22,
                'startColumn' => 5,
                'endColumn' => 66,
                'isPromoted' => false,
                'declaredAtCompileTime' => true,
                'immediateVirtual' => false,
                'immediateHooks' => [
                ],
            ],
            'description' => [
                'declaringClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
                'implementingClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
                'name' => 'description',
                'modifiers' => 2,
                'type' => null,
                'default' => [
                    'code' => '\'Generate a test event and send it to Sentry\'',
                    'attributes' => [
                        'startLine' => 23,
                        'endLine' => 23,
                        'startTokenPos' => 102,
                        'startFilePos' => 581,
                        'endTokenPos' => 102,
                        'endFilePos' => 625,
                    ],
                ],
                'docComment' => null,
                'attributes' => [
                ],
                'startLine' => 23,
                'endLine' => 23,
                'startColumn' => 5,
                'endColumn' => 75,
                'isPromoted' => false,
                'declaredAtCompileTime' => true,
                'immediateVirtual' => false,
                'immediateHooks' => [
                ],
            ],
            'errorMessages' => [
                'declaringClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
                'implementingClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
                'name' => 'errorMessages',
                'modifiers' => 4,
                'type' => null,
                'default' => [
                    'code' => '[]',
                    'attributes' => [
                        'startLine' => 30,
                        'endLine' => 30,
                        'startTokenPos' => 113,
                        'startFilePos' => 760,
                        'endTokenPos' => 114,
                        'endFilePos' => 761,
                    ],
                ],
                'docComment' => '/**
 * Buffer of error messages generated by the Sentry SDK.
 *
 * @var array
 */',
                'attributes' => [
                ],
                'startLine' => 30,
                'endLine' => 30,
                'startColumn' => 5,
                'endColumn' => 32,
                'isPromoted' => false,
                'declaredAtCompileTime' => true,
                'immediateVirtual' => false,
                'immediateHooks' => [
                ],
            ],
        ],
        'immediateMethods' => [
            'handle' => [
                'name' => 'handle',
                'parameters' => [
                ],
                'returnsReference' => false,
                'returnType' => [
                    'class' => 'PHPStan\\BetterReflection\\Reflection\\ReflectionNamedType',
                    'data' => [
                        'name' => 'int',
                        'isIdentifier' => true,
                    ],
                ],
                'attributes' => [
                ],
                'docComment' => '/**
 * Execute the console command.
 *
 * @return int
 */',
                'startLine' => 37,
                'endLine' => 212,
                'startColumn' => 5,
                'endColumn' => 5,
                'couldThrow' => false,
                'isClosure' => false,
                'isGenerator' => false,
                'isVariadic' => false,
                'modifiers' => 1,
                'namespace' => 'Sentry\\Laravel\\Console',
                'declaringClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
                'implementingClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
                'currentClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
                'aliasName' => null,
            ],
            'generateTestException' => [
                'name' => 'generateTestException',
                'parameters' => [
                    'command' => [
                        'name' => 'command',
                        'default' => null,
                        'type' => [
                            'class' => 'PHPStan\\BetterReflection\\Reflection\\ReflectionNamedType',
                            'data' => [
                                'name' => 'string',
                                'isIdentifier' => true,
                            ],
                        ],
                        'isVariadic' => false,
                        'byRef' => false,
                        'isPromoted' => false,
                        'attributes' => [
                        ],
                        'startLine' => 217,
                        'endLine' => 217,
                        'startColumn' => 46,
                        'endColumn' => 60,
                        'parameterIndex' => 0,
                        'isOptional' => false,
                    ],
                    'arg' => [
                        'name' => 'arg',
                        'default' => null,
                        'type' => [
                            'class' => 'PHPStan\\BetterReflection\\Reflection\\ReflectionNamedType',
                            'data' => [
                                'name' => 'array',
                                'isIdentifier' => true,
                            ],
                        ],
                        'isVariadic' => false,
                        'byRef' => false,
                        'isPromoted' => false,
                        'attributes' => [
                        ],
                        'startLine' => 217,
                        'endLine' => 217,
                        'startColumn' => 63,
                        'endColumn' => 72,
                        'parameterIndex' => 1,
                        'isOptional' => false,
                    ],
                ],
                'returnsReference' => false,
                'returnType' => [
                    'class' => 'PHPStan\\BetterReflection\\Reflection\\ReflectionNamedType',
                    'data' => [
                        'name' => 'Exception',
                        'isIdentifier' => false,
                    ],
                ],
                'attributes' => [
                ],
                'docComment' => '/**
 * Generate an example exception to send to Sentry.
 */',
                'startLine' => 217,
                'endLine' => 225,
                'startColumn' => 5,
                'endColumn' => 5,
                'couldThrow' => false,
                'isClosure' => false,
                'isGenerator' => false,
                'isVariadic' => false,
                'modifiers' => 2,
                'namespace' => 'Sentry\\Laravel\\Console',
                'declaringClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
                'implementingClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
                'currentClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
                'aliasName' => null,
            ],
            'logErrorMessageFromSDK' => [
                'name' => 'logErrorMessageFromSDK',
                'parameters' => [
                    'message' => [
                        'name' => 'message',
                        'default' => null,
                        'type' => [
                            'class' => 'PHPStan\\BetterReflection\\Reflection\\ReflectionNamedType',
                            'data' => [
                                'name' => 'string',
                                'isIdentifier' => true,
                            ],
                        ],
                        'isVariadic' => false,
                        'byRef' => false,
                        'isPromoted' => false,
                        'attributes' => [
                        ],
                        'startLine' => 227,
                        'endLine' => 227,
                        'startColumn' => 44,
                        'endColumn' => 58,
                        'parameterIndex' => 0,
                        'isOptional' => false,
                    ],
                ],
                'returnsReference' => false,
                'returnType' => [
                    'class' => 'PHPStan\\BetterReflection\\Reflection\\ReflectionNamedType',
                    'data' => [
                        'name' => 'void',
                        'isIdentifier' => true,
                    ],
                ],
                'attributes' => [
                ],
                'docComment' => null,
                'startLine' => 227,
                'endLine' => 230,
                'startColumn' => 5,
                'endColumn' => 5,
                'couldThrow' => false,
                'isClosure' => false,
                'isGenerator' => false,
                'isVariadic' => false,
                'modifiers' => 1,
                'namespace' => 'Sentry\\Laravel\\Console',
                'declaringClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
                'implementingClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
                'currentClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
                'aliasName' => null,
            ],
            'clearErrorMessagesFromSDK' => [
                'name' => 'clearErrorMessagesFromSDK',
                'parameters' => [
                ],
                'returnsReference' => false,
                'returnType' => [
                    'class' => 'PHPStan\\BetterReflection\\Reflection\\ReflectionNamedType',
                    'data' => [
                        'name' => 'void',
                        'isIdentifier' => true,
                    ],
                ],
                'attributes' => [
                ],
                'docComment' => null,
                'startLine' => 232,
                'endLine' => 235,
                'startColumn' => 5,
                'endColumn' => 5,
                'couldThrow' => false,
                'isClosure' => false,
                'isGenerator' => false,
                'isVariadic' => false,
                'modifiers' => 4,
                'namespace' => 'Sentry\\Laravel\\Console',
                'declaringClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
                'implementingClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
                'currentClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
                'aliasName' => null,
            ],
            'printDebugTips' => [
                'name' => 'printDebugTips',
                'parameters' => [
                ],
                'returnsReference' => false,
                'returnType' => [
                    'class' => 'PHPStan\\BetterReflection\\Reflection\\ReflectionNamedType',
                    'data' => [
                        'name' => 'void',
                        'isIdentifier' => true,
                    ],
                ],
                'attributes' => [
                ],
                'docComment' => null,
                'startLine' => 237,
                'endLine' => 255,
                'startColumn' => 5,
                'endColumn' => 5,
                'couldThrow' => false,
                'isClosure' => false,
                'isGenerator' => false,
                'isVariadic' => false,
                'modifiers' => 4,
                'namespace' => 'Sentry\\Laravel\\Console',
                'declaringClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
                'implementingClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
                'currentClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
                'aliasName' => null,
            ],
        ],
        'traitsData' => [
            'aliases' => [
            ],
            'modifiers' => [
            ],
            'precedences' => [
            ],
            'hashes' => [
            ],
        ],
    ],
]);
